export const FETCH_MOVIES = "FETCH_MOVIES";
export const CREATE_NOMINATION = "CREATE_NOMINATION";
export const DELETE_NOMINATION = "DELETE_NOMINATION";
export const FETCH_NOMINATIONS = "FETCH_NOMINATIONS";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
